-- Migration to add category and score tie-breaker support
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS category VARCHAR(50) DEFAULT 'GRAND_SLAM';
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS category_custom VARCHAR(255);
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS format VARCHAR(50) DEFAULT 'SIMPLES';
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS sets_format INTEGER DEFAULT 3;
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS size INTEGER DEFAULT 128;
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS has_seeds BOOLEAN DEFAULT TRUE;
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS has_qualifiers BOOLEAN DEFAULT TRUE;
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS has_wildcards BOOLEAN DEFAULT TRUE;
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS has_byes BOOLEAN DEFAULT TRUE;

ALTER TABLE predictions ADD COLUMN IF NOT EXISTS is_score_correct BOOLEAN DEFAULT FALSE;
