-- Add columns to tournaments
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS category VARCHAR(50) DEFAULT 'GRAND_SLAM';
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS category_custom VARCHAR(255);
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS format VARCHAR(50) DEFAULT 'SIMPLES';
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS sets_format INTEGER DEFAULT 3;
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS size INTEGER DEFAULT 128;
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS has_seeds BOOLEAN DEFAULT TRUE;
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS has_qualifiers BOOLEAN DEFAULT TRUE;
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS has_wildcards BOOLEAN DEFAULT TRUE;
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS has_byes BOOLEAN DEFAULT TRUE;
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS champion_id INTEGER REFERENCES players(id);
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS runner_up_id INTEGER REFERENCES players(id);

-- Add columns to bracket_matches
ALTER TABLE bracket_matches ADD COLUMN IF NOT EXISTS player1_type VARCHAR(20) DEFAULT 'PLAYER';
ALTER TABLE bracket_matches ADD COLUMN IF NOT EXISTS player2_type VARCHAR(20) DEFAULT 'PLAYER';
ALTER TABLE bracket_matches ADD COLUMN IF NOT EXISTS player1_seed INTEGER;
ALTER TABLE bracket_matches ADD COLUMN IF NOT EXISTS player2_seed INTEGER;
